# Generated by Django 2.0.7 on 2018-08-01 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=128)),
                ('coursecode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=64)),
                ('coursesprovided', models.ManyToManyField(blank=True, related_name='dept_courses', to='webdev.course')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webdev.person')),
                ('idnum', models.CharField(max_length=8)),
                ('yremployed', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
            bases=('webdev.person',),
        ),
        migrations.CreateModel(
            name='instudent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webdev.person')),
                ('roll', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
                ('coursestaken', models.ManyToManyField(related_name='course_instudents', to='webdev.course')),
            ],
            bases=('webdev.person',),
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majordegree', models.CharField(max_length=64)),
                ('deptbelong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_degrees', to='webdev.department')),
            ],
        ),
        migrations.CreateModel(
            name='outstudent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webdev.person')),
                ('coursestaken', models.ManyToManyField(blank=True, related_name='course_openstudents', to='webdev.course')),
            ],
            bases=('webdev.person',),
        ),
        migrations.RemoveField(
            model_name='student',
            name='person_ptr',
        ),
        migrations.CreateModel(
            name='admins',
            fields=[
                ('faculty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webdev.faculty')),
                ('username', models.CharField(max_length=16)),
                ('adminpasscode', models.CharField(max_length=16)),
            ],
            bases=('webdev.faculty',),
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.AddField(
            model_name='faculty',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_faculties', to='webdev.course'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdev.faculty'),
        ),
    ]
