# Generated by Django 2.0.7 on 2018-08-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0003_auto_20180802_0156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admins',
            new_name='inadmin',
        ),
    ]
