# Generated by Django 2.0.7 on 2018-08-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0004_auto_20180802_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
