# Generated by Django 2.0.7 on 2018-08-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0005_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='coursesprovided',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='instudent',
            name='coursestaken',
        ),
        migrations.RemoveField(
            model_name='outstudent',
            name='coursestaken',
        ),
    ]
