# Generated by Django 2.0.7 on 2018-08-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0006_auto_20180804_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
