# Generated by Django 2.0.7 on 2018-08-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0005_course'),
        ('webdev', '0007_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='instudent',
            name='coursestaken',
            field=models.ManyToManyField(related_name='course_instudents', to='purelms.course'),
        ),
    ]
