# Generated by Django 2.0.7 on 2018-08-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0005_course'),
        ('webdev', '0008_instudent_coursestaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='coursesprovided',
            field=models.ManyToManyField(blank=True, related_name='dept_courses', to='purelms.course'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_faculties', to='purelms.course'),
        ),
        migrations.AddField(
            model_name='outstudent',
            name='coursestaken',
            field=models.ManyToManyField(blank=True, related_name='course_openstudents', to='purelms.course'),
        ),
    ]
