# Generated by Django 2.0.7 on 2018-08-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0009_auto_20180804_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
