# Generated by Django 2.0.7 on 2018-08-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0010_delete_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='courses',
        ),
    ]
