# Generated by Django 2.0.7 on 2018-08-07 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0012_faculty_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='deptbelong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descipline', to='webdev.department'),
        ),
    ]
