# Generated by Django 2.0.7 on 2018-08-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0013_auto_20180808_0213'),
        ('dashboard', '0002_mycourses_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mycourses',
            new_name='mycourse',
        ),
    ]
