# Generated by Django 2.0.7 on 2018-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webdev', '0004_auto_20180802_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.IntegerField()),
                ('time_period', models.CharField(max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hidden', models.BooleanField()),
                ('listed', models.BooleanField()),
                ('accepts_enrollment', models.BooleanField(default=True)),
                ('enrollment_approval_required', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(to='webdev.instudent')),
            ],
        ),
    ]
