# Generated by Django 2.0.7 on 2018-08-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0002_remove_course_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_approval_required',
        ),
    ]
