# Generated by Django 2.0.7 on 2018-08-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0003_remove_course_enrollment_approval_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
