# Generated by Django 2.0.7 on 2018-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accepts_enrollment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time_period',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
