# Generated by Django 2.0.7 on 2018-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0006_auto_20180804_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='coursename',
        ),
        migrations.AddField(
            model_name='course',
            name='coursecode',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
