# Generated by Django 2.0.7 on 2018-08-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0007_auto_20180805_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursename',
            new_name='name',
        ),
    ]
