# Generated by Django 2.0.7 on 2018-08-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0008_auto_20180805_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursecode',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
