# Generated by Django 2.0.7 on 2018-08-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0009_auto_20180805_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='internal_only',
            field=models.BooleanField(default=False),
        ),
    ]
