# Generated by Django 2.0.7 on 2018-08-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0010_course_internal_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Amateur', 'Introductory'), ('Learner', 'Intermediate'), ('Pro', 'Advanced')], default='1', max_length=20),
        ),
    ]
