# Generated by Django 2.0.7 on 2018-08-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0011_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Amateur', 'Introductory'), ('Learner', 'Intermediate'), ('Pro', 'Advanced')], default='Introductory', max_length=20),
        ),
    ]
