# Generated by Django 2.0.7 on 2018-08-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purelms', '0012_auto_20180808_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Introductory', 'Introductory'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Introductory', max_length=20),
        ),
    ]
